books/urls.py
from django.urls import path
from . import views


app_name = 'books'
urlpatterns = [
    path('nf/', views.NfListView.as_view(), name="nf_list"),
    path('nf/<int:pk>/', views.NfDetailView.as_view(), name="nf_detail"),
    path('nf/new', views.NfCreateView.as_view(), name='nf_new'),
    path('nf/<int:pk>/update', views.NfUpdateView.as_view(), name='nf_update'),
    path('nf/<int:pk>/delete', views.NfDeleteView.as_view(), name='nf_delete'),

    path('oppkg/', views.OppkgList.as_view(), name="oppkg_list"),
    path('oppkg/<int:pk>/', views.OppkgDetail.as_view(), name="oppkg_detail"),
    path('oppkg/create', views.OppkgCreate.as_view(), name='oppkg_create'),
    path('oppkg/add', views.OppkgAdd.as_view(), name='oppkg_add'),
    path('oppkg/<int:pk>/update', views.OppkgUpdate.as_view(), name='oppkg_update'),
    path('oppkg/<int:pk>/delete', views.oppkg_delete, name='oppkg_delete'),
    path('search/<str:q>/', views.OppkgSearch.as_view()),

    path('subs/', views.SubsList.as_view(), name="subs_list"),
    path('subs/<int:pk>/', views.SubsDetail.as_view(), name="subs_detail"),
    path('subs/create', views.SubsCreate.as_view(), name='subs_create'),
    path('subs/<int:pk>/update', views.SubsUpdate.as_view(), name='subs_update'),
    path('subs/<int:pk>/delete', views.SubsDelete.as_view(), name='subs_delete'),

    # /books/
    path('', views.BooksModelView.as_view(), name='index'),

    # /books/book/
    path('book/', views.BookList.as_view(), name='book_list'),

    # /books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # /books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # /books/book/99/
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/99/
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher/99/
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('books/', include('books.urls'))
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),    # URL alias , 다른 곳에서는 pybo:index 이렇게 사용
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('test/', views.blog_test),
]

books/models.py
from django.db import models
from django.urls import reverse
import gettext as _
from django.contrib.auth.models import User

class Nf(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Operator(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class SwPackage(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.name

class Oppkg(models.Model):
    operator = models.ForeignKey(Operator, on_delete=models.SET_NULL, null=True)
    sw_pkg = models.ForeignKey(SwPackage, on_delete=models.SET_NULL, null=True)
    nfs = models.ManyToManyField(Nf)
    sess_5gm = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Operators and Packages'
        ordering = ['created_at',]

    def __str__(self) -> str:
        return self.operator.name + " : " + self.sw_pkg.name
    
    def get_absolute_url(self):
        return reverse("books:oppkg_detail", kwargs={"pk": self.pk})
    
    
class Subscriber(models.Model):
    oppkg = models.ForeignKey(Oppkg, on_delete=models.CASCADE)
    year = models.IntegerField()
    num_5gm = models.IntegerField()
    num_4gm = models.IntegerField()
    num_5gf = models.IntegerField()

    class Meta:
        verbose_name = '가입자수와 Tput'
        ordering = ['oppkg', 'year']

    def __str__(self) -> str:
        return self.oppkg.operator.name + " : " + self.oppkg.sw_pkg.name + " (Year " + str(self.year) + ")"
    
    def get_absolute_url(self):
        return reverse("books:subs_detail", kwargs={"pk": self.pk})
    


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('books:book_detail', args=[self.pk])
        # return reverse('books:book_detail', kwargs={'pk':self.pk}) 와 동일

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('books:author_detail', args=[self.pk])


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('books:publisher_detail', args=[self.pk])

books/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from books.models import Nf, Oppkg, Subscriber

class NfForm(forms.ModelForm):
    class Meta:
        model = Nf
        fields = ['name']


class OppkgForm(forms.ModelForm):
    class Meta:
        model = Oppkg
        fields = ['operator','sw_pkg','nfs', 'sess_5gm', 'comment']

        widgets = {
             'operator': forms.Select(attrs={'class': 'form-select form-select-sm'}),
             'sw_pkg': forms.Select(attrs={'class': 'form-select form-select-sm'}),
             'nfs': forms.CheckboxSelectMultiple(),
             'sess_5gm': forms.NumberInput(attrs={'class': 'form-control'}),
             'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'operator': '사업자 : ',
            'sw_pkg': 'PKG : ',
            'nfs': 'NF 지원 : ',
            'sess_5gm' : '5G mobile session수 : '
        }

SubsInlineFormSet = inlineformset_factory(Oppkg, Subscriber,
    fields = ['year', 'num_5gm', 'num_4gm', 'num_5gf'],
    extra = 3
)

books/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from books.forms import NfForm, OppkgForm, SubsInlineFormSet
from books.models import Book, Author, Oppkg, Publisher, Subscriber, Nf
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.contrib import messages

class NfListView(ListView):
    model = Nf
    
class NfDetailView(DetailView):
    model = Nf

class NfCreateView(LoginRequiredMixin, CreateView):
    model = Nf
    form_class = NfForm
    #fields = ['name',]  # 항상 넣어줘야 함
    success_url = '/books/nf/'

class NfUpdateView(UpdateView):
    model = Nf
    form_class = NfForm
    template_name = "books/nf_form.html"
    # fields = ['name',]  # 항상 넣어줘야 함
    success_url = '/books/nf/'

class NfDeleteView(DeleteView):
    model = Nf
    def get_success_url(self):
        return reverse('books:nf_list')
# 없으면 nf_confirm_delete.html 찾음

class OppkgList(ListView):
    model = Oppkg

    def get_context_data(self, **kwargs):
        context = super(OppkgList, self).get_context_data()
        context['subscribers'] = Subscriber.objects.all()
        return context

# OppkgList를 상속받아 오버라이딩
class OppkgSearch(OppkgList):
    def get_queryset(self):
        q = self.kwargs['q']
        oppkg_list = Oppkg.objects.filter(
            Q(operator__name__contains=q) | Q(sw_pkg__name__contains=q) | Q(nfs__name__contains=q)
        ).distinct()
        return oppkg_list
        
    def get_context_data(self, **kwargs):
        context = super(OppkgSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

class OppkgDetail(DetailView):
    model = Oppkg

    def get_context_data(self, **kwargs):
        context = super(OppkgDetail, self).get_context_data()
        context['subscribers'] = Subscriber.objects.filter(oppkg__pk=self.kwargs['pk'])
        return context

class OppkgCreate(LoginRequiredMixin, CreateView):
    model = Oppkg  # tempalte_name 안쓰면 oppkg_form.html 임
    template_name = "books/oppkg_form.html" # 없으면 모델명_form.html
    form_class = OppkgForm
    
    # 인증되고 스테프나 superuser만 신규등록 가능하고 등록자 기록함
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user # user를 자동으로 채움
            return super(OppkgCreate, self).form_valid(form)
        else:
            return redirect('books:oppkg_list')

    def get_success_url(self):
        return reverse('books:oppkg_list')

class OppkgAdd(LoginRequiredMixin, CreateView):
    model = Oppkg
    template_name = "books/oppkg_add_form.html"
    form_class = OppkgForm

    def get_context_data(self, **kwargs):
        context = super(OppkgAdd, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SubsInlineFormSet(self.request.POST)
        else:
            context['formset'] = SubsInlineFormSet(initial=[
                {'year': 1,'num_5gm': 0,'num_4gm': 0,'num_5gf': 0,}
                ])
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            current_user = self.request.user
            if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
                form.instance.author = current_user # user를 자동으로 채움
            else:
                return self.render_to_response(self.get_context_data(form=form))
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('books:oppkg_list')
        else:
            return self.render_to_response(self.get_context_data(form=form))


class OppkgUpdate(UpdateView):
    model = Oppkg
    form_class = OppkgForm
    template_name = "books/oppkg_update.html" # 헷갈리니 넣어서 분리하자.
    
    # 작성자나 superuser만 업데이트하도록
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and (request.user == self.get_object().author or request.user.is_superuser):
            return super(OppkgUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse('books:oppkg_list')

def oppkg_delete(request, pk):
    oppkg = get_object_or_404(Oppkg, pk=pk)
    messages.warning(request,"지웠습니다.")
    if request.user.is_authenticated and (request.user == oppkg.author or request.user.is_superuser):
        oppkg.delete()
        return redirect('books:oppkg_list')
    else:
        raise PermissionDenied

# class OppkgDelete(DeleteView):
#     model = Oppkg
#     def get_success_url(self):
#         return reverse('books:oppkg_list')

class SubsList(ListView):
    model = Subscriber

class SubsDetail(DetailView):
    model = Subscriber

class SubsCreate(CreateView):
    model = Subscriber  # tempalte_name 안쓰면 oppkg_form.html 임
    fields = "__all__"

    def get_success_url(self):
        return reverse('books:subs_list')

class SubsUpdate(UpdateView):
    model = Subscriber
    fields = "__all__"
    
    def get_success_url(self):
        return reverse('books:subs_list')

class SubsDelete(DeleteView):
    model = Subscriber
    def get_success_url(self):
        return reverse('books:subs_list')

#--- TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context


#--- ListView
class BookList(ListView):
    model = Book


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


#--- DetailView
class BookDetail(DetailView):
    model = Book


class AuthorDetail(DetailView):
    model = Author


class PublisherDetail(DetailView):
    model = Publisher

templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email: {{ object.email }}</li>

{% endblock content %}

templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.title }}</h1>
<br>
<li>Authors: 
{% for author in object.authors.all %}
  {{ author }}
  {% if not forloop.last %},{% else %}{% endif %}
{% endfor %}
</li>

<li>Publisher: {{ object.publisher }}</li>
<li>Publication date: {{ object.publication_date }}</li>

{% endblock content %}

templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
            <li><a href="{{ book.get_absolute_url }}">{{ book.title }}-alter way</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
            <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/nf_form.html
{% extends "base_dimen.html" %}

{% block content %}
    <h2>NF Create</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" name="submit">
{% endblock content %}

templates/books/oppkg_add_form.html
{% extends "base_dimen.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Oppkg - Subs Create</h2>
    
        <form method="post" >
            {% csrf_token %}
            {% if form.errors %}
            <p class="errornote">Wrong! Please correct the FORM erros</p>
            {% endif %}
            {% if formset.errors %}
            <p class="errornote">Wrong! Please correct the FORMSET erros</p>
            {% endif %}

            <h4> Oppkg add </h4>
            <div class="mb-3 row">
                <div class="col-md-2 mb-0">
                  {{ form.operator | as_crispy_field }}
                </div>
                <div class="col-md-2 mb-0">
                  {{ form.sw_pkg | as_crispy_field }}
                </div>
            </div>
            <br>
            <div class="mb-3 row">
                <div class="col-md-6 mb-0">
                    {{ form.nfs | as_crispy_field }}
                </div>
                <div class="col-md-2 mb-0">
                    {{ form.sess_5gm | as_crispy_field }}
                </div>
            </div>
            <hr>
            <h4> Subs add </h4>
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.id }}
            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.year.label_tag }} {{ form.year }}
                </div>
                <div class="form-row">
                    {{ form.num_5gm.label_tag }} {{ form.num_5gm }}
                </div>
                <div class="form-row">
                    {{ form.num_4gm.label_tag }} {{ form.num_4gm }}
                </div>
                <div class="form-row">
                    {{ form.num_5gf.label_tag }} {{ form.num_5gf }}
                </div>
            </fieldset>
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="submit" name='submit' value='Save' class="btn btn-primary">생성</button>
            </div>
        </form>
    

{% endblock content %}

templates/books/oppkg_confirm_delete.html
{% extends "base_dimen.html" %}

{% block content %}
    <h2>Oppkg Delete</h2>
    <h6> this is : {{ object.id }} : {{ object.nfs.all }}
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}

    <button type="submit" class="btn btn-primary">삭제</button>
    </form>
    <a href="{% url 'books:oppkg_list' %}" class="btn btn-secondary">삭제안함</a>
{% endblock content %}

templates/books/oppkg_detail.html
{% extends "base_dimen.html" %}

{% block content %}
    <h2>Oppkg Detail</h2>
    <ul class="list-group">
        <li class="list-group-item">(pk: {{ object.pk }}) : {{ object }}</li>
        <li class="list-group-item">NFs :{{ object.nfs.all }}</li>
        <li class="list-group-item">Created at :{{ object.created_at }}</li>
        <li class="list-group-item">Updated at :{{ object.updated_at }}</li>
        <li class="list-group-item">Author :{{ object.author }}</li>
    </ul>
    <ul>
    {% for subscriber in subscribers %}
    <li>{{ subscriber.year }}:{{ subscriber.num_5gm}}:{{ subscriber.num_4gm}}</li>
    {% endfor %}
    </ul>
    <hr>
    {% comment %} 버튼은 로그인한 작성자나 superuser에게만 {% endcomment %}
    {% if user.is_authenticated %}
    {% if user == object.author or user.is_superuser %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'books:oppkg_update' object.pk %}" class="btn btn-secondary">Oppkg 수정</a>
            <a role="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</a>
        </div>
    {% endif %}
    {% endif %}

    {% comment %} Modal {% endcomment %}
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">삭제</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <del>{{ object }}</del>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a role="button" href="{% url 'books:oppkg_delete' object.id %}" class="btn btn-danger" >Delete</a>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

templates/books/oppkg_form2.html
{% extends "base_dimen.html" %}

{% block content %}
    <h2>Oppkg Create</h2>
    <div class='form-group container'>
        <form method="post" >
            {% csrf_token %}
            <div class="row g-3 align-items-center my-3">
                <div class="col-auto">
                    {{ form.operator.label }} {{ form.operator }}
                </div>
                <div class="col-auto">
                    {{ form.sw_pkg.label }} {{ form.sw_pkg }}
                </div>
            </div>
            {{ form.nfs.label }}
            <div class="btn-group my-3" data-bs-toggle="buttons"> 
                
                {% for checkbox in form.nfs %}
                    <label class="btn btn-outline-dark btn-sm">
                    {{ checkbox.tag }} {{ checkbox.choice_label }}
                    </label>
                {% endfor %}
            </div><br><hr>
        <button type="submit" name='submit' value='Save' class="btn btn-primary">생성</button>
        </form>
    </div>

{% endblock content %}

templates/books/oppkg_update.html
{% extends "base_dimen.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Oppkg Update</h2>
    <h6> this is : {{ object.id }} : {{ object.nfs.all }}
    <form method="POST" >
        {% csrf_token %}
        {{ form | crispy }}

    <button type="submit" class="btn btn-primary" name="submit">변경</button>
{% endblock content %}

templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address: {{ object.address }}</li>

{% endblock content %}

templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
            <li><a href="{{ publisher.get_absolute_url }}">{{ publisher.name }}-alter way</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/subscriber_confirm_delete.html
{% extends "base_dimen.html" %}

{% block content %}
    <h2>Subscriber Delete</h2>
    <h6> this is : {{ object.id }} : {{ object }}
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}

    <button type="submit" class="btn btn-primary">삭제</button>
    </form>
    <a href="{% url 'books:subs_list' %}" class="btn btn-secondary">삭제안함</a>
{% endblock content %}

templates/books/subscriber_detail.html
{% extends "base_dimen.html" %}
{% load humanize %}
{% block content %}
    <h2>Subscriber Detail</h2>
    <ul>
        <li>(pk: {{ object.pk }}) : {{ object }}</li>
        <li>{{ object.year }}</li>
        <li>{{ object.num_5gm | intcomma }}</li>
        <li>{{ object.num_4gm | intcomma }}</li>
        <li>{{ object.num_5gf | intcomma }}</li>
    </ul>
    <a href="{% url 'books:subs_update' object.pk %}" class="btn btn-secondary">수정</a>
    <a href="{% url 'books:subs_delete' object.id %}" class="btn btn-danger">삭제</a>
        

{% endblock content %}