books/urls.py
from django.urls import path
from . import views


app_name = 'books'
urlpatterns = [
    path('nf/', views.NfListView.as_view(), name="nf_list"),
    path('nf/<int:pk>/', views.NfDetailView.as_view(), name="nf_detail"),
    path('nf/new', views.NfCreateView.as_view(), name='nf_new'),
    path('nf/<int:pk>/update', views.NfUpdateView.as_view(), name='nf_update'),
    path('nf/<int:pk>/delete', views.NfDeleteView.as_view(), name='nf_delete'),

    path('oppkg/', views.OppkgList.as_view(), name="oppkg_list"),
    path('oppkg/<int:pk>/', views.OppkgDetail.as_view(), name="oppkg_detail"),
    path('oppkg/create', views.OppkgCreate.as_view(), name='oppkg_create'),
    path('oppkg/add', views.OppkgAdd.as_view(), name='oppkg_add'),
    path('oppkg/<int:pk>/update', views.OppkgUpdate.as_view(), name='oppkg_update'),
    path('oppkg/<int:pk>/delete', views.oppkg_delete, name='oppkg_delete'),
    path('search/<str:q>/', views.OppkgSearch.as_view()),

    path('subs/', views.SubsList.as_view(), name="subs_list"),
    path('subs/<int:pk>/', views.SubsDetail.as_view(), name="subs_detail"),
    path('subs/create', views.SubsCreate.as_view(), name='subs_create'),
    path('subs/<int:pk>/update', views.SubsUpdate.as_view(), name='subs_update'),
    path('subs/<int:pk>/delete', views.SubsDelete.as_view(), name='subs_delete'),

    # /books/
    path('', views.BooksModelView.as_view(), name='index'),

    # /books/book/
    path('book/', views.BookList.as_view(), name='book_list'),

    # /books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # /books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # /books/book/99/
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/99/
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher/99/
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('books/', include('books.urls'))
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),    # URL alias , 다른 곳에서는 pybo:index 이렇게 사용
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('test/', views.blog_test),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 사용-->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/base_books.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link href="{% static 'sidebars.css' %}" rel="stylesheet">
    <title>{% block title %}Books{% endblock %}</title>
</head>

<body>
<div class="row">
  <div class="flex-shrink-0 p-3 col-md-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <span class="fs-5 fw-semibold">Collapsible</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Overview</a></li>
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Updates</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          Orders
        </button>
        <div class="collapse" id="orders-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">New</a></li>
            <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Processed</a></li>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
    </ul>
  </div>

  <div class="row col-md-9">
  <div class="col-md-3">
    <input type="text" class="form-control" placeholder="First" aria-label="First">
  </div>
  <div class="col-md-3">
    <input type="text" class="form-control" placeholder="2nd" aria-label="Last name">
  </div>
     <div class="col-md-3">
    <input type="text" class="form-control" placeholder="3rd" aria-label="Test item">
  </div>
     <div class="col-md-3">
    <input type="text" class="form-control" placeholder="4th" aria-label="4th">
  </div>
  </div>
</div>
      <div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
  <label class="form-check-label" for="inlineCheckbox1">1</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
  <label class="form-check-label" for="inlineCheckbox2">2</label>
</div>



    <div id="sidebar">

        <ul>
            <li><a href="/books/">Book's Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>

        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
<!-- Bootstrap JS -->
<!--<script src="{% static 'bootstrap.min.js' %}"></script>-->
      <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'sidebars.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/base_dimen copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link href="{% static 'sidebars.css' %}" rel="stylesheet">
    <title>Dimensioning Test</title>
</head>

<body>
<div class="row">
  <div class="flex-shrink-0 p-3 col-md-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <span class="fs-5 fw-semibold">Collapsible</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Network Function
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'books:nf_list' %}" class="link-dark d-inline-flex text-decoration-none rounded">List</a></li>
            <li><a href="{% url 'books:nf_new' %}" class="link-dark d-inline-flex text-decoration-none rounded">Create</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          Operator and Package
        </button>
        <div class="collapse" id="orders-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'books:oppkg_list' %}" class="link-dark d-inline-flex text-decoration-none rounded">List</a></li>
            <li><a href="{% url 'books:oppkg_create' %}" class="link-dark d-inline-flex text-decoration-none rounded">Create</a></li>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="row">

      <div id="content">
          {% block content %}{% endblock %}
      </div>

      <div class="col-md-3">
        <input type="text" class="form-control" placeholder="First" aria-label="First">
      </div>
      <div class="col-md-3">
        <input type="text" class="form-control" placeholder="2nd" aria-label="Last name">
      </div>
      <div class="col-md-3">
        <input type="text" class="form-control" placeholder="3rd" aria-label="Test item">
      </div>
      <div class="col-md-3">
        <input type="text" class="form-control" placeholder="4th" aria-label="4th">
      </div>
    
    
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
        <label class="form-check-label" for="inlineCheckbox2">2</label>
      </div>
    </div>
  </div>
</div>
<!-- Bootstrap JS -->
<!--<script src="{% static 'bootstrap.min.js' %}"></script>-->
      <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'sidebars.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/base_dimen.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link href="{% static 'sidebars.css' %}" rel="stylesheet">
    <title>Dimensioning Test</title>
</head>

<body>
<div class="row">
  <div class="flex-shrink-0 p-3 col-md-3 bg-light border-end" style="width: 280px;">
    <a href="{% url 'books:oppkg_list' %}" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <span class="fs-5 fw-semibold">Dimensioning</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Network Function
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'books:nf_list' %}" class="link-dark d-inline-flex text-decoration-none rounded">List</a></li>
            <li><a href="{% url 'books:nf_new' %}" class="link-dark d-inline-flex text-decoration-none rounded">Create</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="true">
          Operator and Package
        </button>
        <div class="collapse show" id="orders-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'books:oppkg_list' %}" class="link-dark d-inline-flex text-decoration-none rounded">List</a></li>
            <li><a href="{% url 'books:oppkg_create' %}" class="link-dark d-inline-flex text-decoration-none rounded">Create</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders2-collapse" aria-expanded="true">
          Subscriber
        </button>
        <div class="collapse show" id="orders2-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="{% url 'books:subs_list' %}" class="link-dark d-inline-flex text-decoration-none rounded">List</a></li>
            <li><a href="{% url 'books:subs_create' %}" class="link-dark d-inline-flex text-decoration-none rounded">Create</a></li>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
    </ul>
    
  </div>
  <div class="col-md-9">
    
    <div class="row container">
      <div id="content">
          {% block content %}{% endblock %}
      </div>
      
    </div>
  </div>
</div>
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those fields below.  
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
        {{ message }}
    </div>
{% endfor %}
<!-- Bootstrap JS -->
<!--<script src="{% static 'bootstrap.min.js' %}"></script>-->
      <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'sidebars.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">게시판</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/test11.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, Bootstrap Table!</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.css">
  </head>
  <body>
    <table data-toggle="table">
      <thead>
        <tr>
          <th>Item ID</th>
          <th>Item Name</th>
          <th>Item Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Item 1</td>
          <td>$1</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Item 2</td>
          <td>$2</td>
        </tr>
      </tbody>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.js"></script>
  </body>
</html>